export enum CartItemActionType {
  SUCCESS = "SUCCESS",
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  DELETED = "DELETED",
  NOT_FOUND = "NOT_FOUND",
}

export enum UsersActionType {
  SUCCESS = "SUCCESS",
  CREATED = "CREATED",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  CONFLICT = "CONFLICT",
  FORBIDDEN = "FORBIDDEN",
}
